FLASK_APP=app.py
FLASK_ENV=development
FLASK_DEBUG=True
RECAPTCHA_PUBLIC_KEY = '6LdJYR4pAAAAAOmQzWwtH5MHj0HCj8AXcaBsesgJ'
RECAPTCHA_PRIVATE_KEY= '6LdJYR4pAAAAAFOaeMvNbjZpcJWPjyps5oiVBIuG'
SECRET_KEY = '124456789'